---
- hosts: localhost
  vars:
     region: us-east-1
     image_id: ami-04d29b6f966df1537
     instance_type: t2.micro
     key_name: ma_ansible_test_key_pair
  tasks:
  - name: List a specific EC2 instance
    ec2_instance_info:
      ec2_region: "{{region}}"
    register: result

  - name: List several EC2 instances according to their name tag
    ec2_instance_info:
      ec2_region: "{{region}}"
      names:
        - master
        - nodes
    register: result