---
- name: ping them all
  hosts: _Nodes
  remote_user: ansible
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh
  vars:
    ansible_ssh_private_key_file: "../../Saws-private.pem"
  tasks:
    - name: pinging
      ping:
