---
- name: ping them all
  hosts: all
  remote_user: ansible
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh
  tasks:
    - name: pinging
      ping:
  vars:
    ansible_ssh_private_key_file: "/home/ansible/.ssh/id_rsa"
    