---
- name: ping them all
  hosts: _Nodes
  remote_user: ansible
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh
  tasks:
    - name: pinging
      ping:
