---
- hosts: _Master
  remote_user: ubuntu
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh
  tasks:
   - name: Intilizing Kubernetes Cluster
     command: kubeadm init  "--ignore-preflight-errors=Mem" "--pod-network-cidr=172.10.1.0/24" "--apiserver-advertise-address=0.0.0.0" "--apiserver-cert-extra-sans={{ ansible_ssh_host }}"
     run_once: true
   - pause: seconds=30
   - name: Create directory for kube config.
     become_user: ansible
     become_method: sudo
     become: yes
     file: 
       path: "lookup('env','HOME')+.kube"
       state: directory
       mode: 0755
   - name: Copy /etc/kubernetes/admin.conf to user's home directory /home/.kube/config.
     become_user: root
     become_method: sudo
     become: yes
     copy:
       src: /etc/kubernetes/admin.conf
       dest: "lookup('env','HOME')+.kube/config"
       remote_src: yes
       mode: '0644'
   - pause: seconds=10
   - name: Remove the cache directory.
     become_user: ansible
     become_method: sudo
     become: yes
     file: 
       path: "lookup('env','HOME')+.kube/cache"
       state: absent
   - name: Create Pod Network & RBAC.
     become_user: ansible
     become_method: sudo
     become: yes
     command: "{{ item }}"
     with_items: 
        - kubectl apply -f  "https://cloud.weave.works/k8s/net"
   - pause: seconds=30
   - name: Get the token for joining the nodes with Kuberentes master.
     shell: kubeadm token create  --print-join-command
     register: kubernetes_join_command
   - debug:
       msg: "{{ kubernetes_join_command.stdout }}"
   - name: Copy join command to local file.
     local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="../kubernetes_join_command" mode=0777
...