---
- hosts: _Master
  remote_user: ubuntu
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh
  tasks:
  - name: Intilizing Kubernetes Cluster
    command: kubeadm init  "--ignore-preflight-errors=Mem" 
    run_once: true
  - pause: seconds=30

  - name: Creating the required directories
    shell:
      cmd: mkdir -p $HOME/.kube
    register: KubeAdm_Commands_status

  - name: KubeAdm Commands Status
    debug:
          msg: "{{ KubeAdm_Commands_status }}"

  # Copying the required stuff after Kubeadm init successful
  - name: Copy command of KubeAdm
    shell:
      cmd: sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    register: KubeAdm_CP_Commands_status

  - name: KubeAdm Copy Commands Status
    debug:
          msg: "{{ KubeAdm_CP_Commands_status }}"  
  - pause: seconds=10
  # Changing the ownership of the directories
  - name: Changing ownership of directories
    shell:
      cmd: sudo chown $(id -u):$(id -g) $HOME/.kube/config
    register: KubeAdm_Chaning_Ownership_Commands_status

  - name: KubeAdm Changing ownership Commands Status
    debug:
        msg: "{{ KubeAdm_Chaning_Ownership_Commands_status }}"

  # Adding the support of Flannel Network for Overlay Network
  - name: Adding Flannel Network
    command:
      cmd: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
    register: Flannel_status

  - name: Flannel Network Status
    debug:
        msg: "Flannel Network failed => {{ Flannel_status.failed }}"
   - pause: seconds=30
  - name: Get the token for joining the nodes with Kuberentes master.
    shell: kubeadm token create  --print-join-command
    register: kubernetes_join_command
  - debug:
         msg: "{{ kubernetes_join_command.stdout }}"
  - name: Copy join command to local file.
    local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="../kubernetes_join_command" mode=0777
...